name: workflow_last_page_7d5ea4c0-fea9-458d-ae86-92821114b19f
label: workflow last page output
description: quick output page that workflow is complete

type: template

extends:

labels:
  collection:
    - HomeSkillet lib

variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: hidden

snippets:
  - name: workflow_output
    file: workflow_output.txt