# gold security templates for top level security including threat, URL, or WF subscriptions
# includes an additional security rule for strict file blocking of unknown url category

name: homeskillet_vwire_panos_v10
label: v10.0 Step 2 - HomeSkillet network configuration - vwire
description: "** LOAD BASELINE FIRST ** v10.0 Home Skillet Internet Gateway network that loads after HomeSkillet baseline"

type: panos

labels:
    collection:
      - lib

variables:
  - name: INTF_UNTRUST
    description: internet Interface
    default: ethernet1/1
    type_hint: dropdown
    source: interface_names
  - name: INTF_TRUST
    description: internal Interface
    default: ethernet1/2
    type_hint: dropdown
    source: interface_names
  - name: ZONE_TRUST
    description: internal zone name
    default: internal
    type_hint: text
  - name: ZONE_UNTRUST
    description: internet zone name
    default: internet
    type_hint: text
  
snippets:
  - name: network_profiles-network-profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles
    file: network_profiles.xml
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: vwire
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-wire
    file: vwire.xml