name: homeskillet_base_panos_v90_5fdbc623-2891-4937-a577-d0aea59065cc

label: v9.0 Step 1 - HomeSkillet baseline based on IronSkillet

description: |
  "** LOAD ME FIRST ** Homeskillet baseline configuration extracted from IronSkillet"

type: panos

labels:
  help_link: https://homeskillet.readthedocs.io/en/90dev/ironskillet_deltas.html
  collection:
    - lib

variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text
  - name: NTP_1
    description: Network Time Protocol Server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: Network Time Protocol Server 2
    default: 1.pool.ntp.org
    type_hint: text
  - name: SINKHOLE_IPV4
    description: sinkhole FQDN IPv4
    default: sinkhole.paloaltonetworks.com
    type_hint: text
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text
  - name: API_KEY_LIFETIME
    description: lifetime for the api key in minutes
    default: 525600
    type_hint: text
# option built into the templates to ignore the panw published external dynamic lists security rules
# should ONLY be excluded based on licensing limitations outside of best practices
# when 'yes' (default) will include the EDL rule
  - name: INCLUDE_PAN_EDL
    description: include the predefined Palo Alto Networks external lists security rules
    default: 'no'
    type_hint: dropdown
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'


# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# this is based on IronSkillet noting all snippets are not used in HomeSkillet
snippets:
  - name: device_system
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: device_system.xml
  - name: device_setting
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting
    file: device_setting.xml
  - name: password_complexity
    xpath: /config/mgt-config/password-complexity
    file: password_complexity.xml
  - name: shared_log_settings
    xpath: /config/shared/log-settings
    file: shared_log_settings.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: log_settings_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings/profiles
    file: log_settings_profiles.xml
  - name: profiles_custom_url_category
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/custom-url-category
    file: profiles_custom_url_category.xml
  - name: profiles_decryption
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/decryption
    file: profiles_decryption.xml
  - name: profiles_virus
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus
    file: profiles_virus.xml
  - name: profiles_spyware
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/spyware
    file: profiles_spyware.xml
  - name: profiles_vulnerability
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability
    file: profiles_vulnerability.xml
  - name: profiles_file_blocking
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/file-blocking
    file: profiles_file_blocking.xml
  - name: profiles_url_filtering
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering
    file: profiles_url_filtering.xml
  - name: profiles_wildfire_analysis
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/wildfire-analysis
    file: profiles_wildfire_analysis.xml
  - name: profile_group
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group
    file: profile_group.xml
  - name: default_security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/default-security-rules
    file: rulebase_default_security_rules.xml
  - name: security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase
    file: rulebase_security.xml
  - name: decryption_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/decryption
    file: rulebase_decryption.xml
  - name: zone_protection_profile
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
    file: zone_protection_profile.xml
  - name: reports
    xpath: /config/shared/reports
    file: reports_simple.xml
  - name: report_group_simple
    xpath: /config/shared/report-group
    file: report_group_simple.xml